
server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luowei?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.jc.system.entity